   server:
    tomcat:
      accesslog:
        enabled: true

spring:
  application:
    name: webtest
  datasource:
    url: jdbc:postgresql://localhost:5432/webtest
    username: postgres
    password: psql
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  spring.datasource.url=jdbc:postgresql://localhost:5432/webtest
#  spring.datasource.username=ridwan
