server:
  port: 8089

spring:
  application:
    name: webtest
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/webtest_qja6
    username: ridwan
    password: YxoIXTwv59fnSvk5LXgpCAGUtbIZdTKL
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show: true

#  spring.datasource.url=jdbc:postgresql://localhost:5432/webtest
#  spring.datasource.username=ridwan
