   server:
    tomcat:
      accesslog:
        enabled: true

spring:
  application:
    name: webtest
  datasource:
    url: jdbc:postgresql://dpg-combgl6n7f5s73d7qvj0-a/webtest_qja6
    username: ridwan
    password: YxoIXTwv59fnSvk5LXgpCAGUtbIZdTKL
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  spring.datasource.url=jdbc:postgresql://localhost:5432/webtest
#  spring.datasource.username=ridwan
