
server:
  port: 8089
spring:
  application:
    name: webtest
  datasource:
    url: jdbc:postgresql://dpg-cov3r0acn0vc739sup2g-a.oregon-postgres.render.com/web_test
    username: web_test_user
    password: w5Qa09aqULbilzkYY8nsI1CsTQCjqgx7
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


#  spring.datasource.url=jdbc:postgresql://localhost:5432/webtest
#  spring.datasource.username=ridwan
